project:
  type: website

website:
  title: "GBIF Species Mapper"
  navbar:
    left:
      - href: gbif-species-mapper.qmd
        text: Analysis
      - href: assignment-instructions.qmd
        text: Instructions
      - href: pages/gbif-map.qmd
        text: HCFS GBIF Map

format:
  html:
    theme: cosmo
    toc: true
    code-fold: false
    embed-resources: true

# Publish to docs/ if using GitHub Pages
# output-dir: docs