# complete_gbif_assignment_setup.R
# Run this ONE script to create the entire GitHub repository structure

# Set the target directory
target_dir <- "~/biodiversity-discovery/gbif-assignment"
target_dir <- path.expand(target_dir) # Expand the ~ to full path

cat("Creating GBIF Assignment Repository Structure in:", target_dir, "\n")

# Set working directory to target folder
setwd(target_dir)

# Create directory structure
dirs <- c("data", "outputs", ".github/workflows")
for (dir in dirs) {
  dir.create(dir, recursive = TRUE, showWarnings = FALSE)
}

# Create .gitkeep files for empty directories
file.create("data/.gitkeep")
file.create("outputs/.gitkeep")

# Function to write files
write_file <- function(filename, content) {
  writeLines(content, filename)
  cat("✓ Created:", file.path(target_dir, filename), "\n")
}

# 1. README.md
readme_content <- c(
  "# GBIF Species Occurrence Mapper Assignment",
  "",
  "## Overview",
  "This assignment teaches you to retrieve, analyze, and visualize species occurrence data from GBIF using R and Quarto.",
  "",
  "## Getting Started",
  "1. Accept the GitHub Classroom assignment",
  "2. Clone your repository",
  "3. Open gbif-species-mapper.qmd in RStudio",
  "4. Customize the species parameters",
  "5. Run the analysis and answer questions",
  "",
  "## Required R Packages",
  "install.packages(c(\"rgbif\", \"leaflet\", \"dplyr\", \"DT\", \"htmlwidgets\", \"ggplot2\"))",
  "",
  "## Files",
  "- gbif-species-mapper.qmd - Main assignment notebook",
  "- assignment-instructions.qmd - Detailed instructions",
  "- data/ - Downloaded GBIF data",
  "- outputs/ - Generated maps and reports"
)
write_file("README.md", readme_content)

# 2. .gitignore
gitignore_content <- c(
  "# R",
  ".Rproj.user",
  ".Rhistory",
  ".RData",
  ".Ruserdata",
  "*.Rproj",
  "",
  "# Quarto",
  "/.quarto/",
  "_site/",
  "",
  "# OS",
  ".DS_Store",
  "Thumbs.db"
)
write_file(".gitignore", gitignore_content)

# 3. _quarto.yml
quarto_yml_content <- c(
  "project:",
  "  type: website",
  "",
  "website:",
  "  title: \"GBIF Species Mapper\"",
  "  navbar:",
  "    left:",
  "      - href: gbif-species-mapper.qmd",
  "        text: Analysis",
  "      - href: assignment-instructions.qmd",
  "        text: Instructions",
  "",
  "format:",
  "  html:",
  "    theme: cosmo",
  "    toc: true",
  "    code-fold: false",
  "    embed-resources: true"
)
write_file("_quarto.yml", quarto_yml_content)

# 4. Main Notebook - gbif-species-mapper.qmd
notebook_content <- c(
  "---",
  "title: \"GBIF Species Occurrence Mapper\"",
  "author: \"Your Name Here\"",
  "date: today",
  "format: ",
  "  html:",
  "    toc: true",
  "    code-fold: false",
  "    embed-resources: true",
  "execute:",
  "  warning: false",
  "  message: false",
  "---",
  "",
  "```{r setup}",
  "#| include: false",
  "# Install required packages if not already installed",
  "required_packages <- c(\"rgbif\", \"leaflet\", \"dplyr\", \"DT\", \"htmlwidgets\", \"ggplot2\")",
  "",
  "for (pkg in required_packages) {",
  "  if (!require(pkg, character.only = TRUE)) {",
  "    install.packages(pkg)",
  "    library(pkg, character.only = TRUE)",
  "  }",
  "}",
  "```",
  "",
  "## Student Instructions",
  "",
  "**Customize these parameters for your species:**",
  "",
  "```{r parameters}",
  "# STUDENT CUSTOMIZATION SECTION",
  "# =============================",
  "",
  "# Your target species (use scientific name)",
  "species_name <- \"Puma concolor\"",
  "",
  "# Country code (ISO 2-letter: US, CA, MX, etc. Leave as NULL for worldwide)",
  "country_code <- \"US\"",
  "",
  "# Maximum number of records to retrieve",
  "max_records <- 500",
  "",
  "# Map settings",
  "map_center_lat <- 39.8283  # Adjust for your study area",
  "map_center_lon <- -98.5795",
  "initial_zoom <- 4",
  "```",
  "",
  "## Data Retrieval",
  "",
  "```{r data-retrieval}",
  "cat(\"Searching for:\", species_name, \"\\n\")",
  "",
  "# Get species key from GBIF",
  "species_key <- name_backbone(name = species_name)$usageKey",
  "",
  "if (is.null(species_key)) {",
  "  stop(\"Species not found in GBIF. Check spelling and try again.\")",
  "}",
  "",
  "cat(\"Species key found:\", species_key, \"\\n\")",
  "",
  "# Build search parameters",
  "search_params <- list(",
  "  taxonKey = species_key,",
  "  hasCoordinate = TRUE,",
  "  limit = max_records",
  ")",
  "",
  "# Add country if specified",
  "if (!is.null(country_code)) {",
  "  search_params$country <- country_code",
  "}",
  "",
  "# Retrieve occurrence data",
  "cat(\"Retrieving occurrence data...\\n\")",
  "gbif_data <- do.call(occ_search, search_params)",
  "",
  "# Extract data frame",
  "occurrences <- gbif_data$data",
  "",
  "cat(\"Retrieved\", nrow(occurrences), \"records\\n\")",
  "```",
  "",
  "## Data Summary",
  "",
  "```{r data-summary}",
  "# Display basic statistics",
  "cat(\"Data Summary for\", species_name, \"\\n\")",
  "cat(\"Total records:\", nrow(occurrences), \"\\n\")",
  "cat(\"Date range:\", min(occurrences$eventDate, na.rm = TRUE), \"to\", ",
  "    max(occurrences$eventDate, na.rm = TRUE), \"\\n\")",
  "cat(\"Countries represented:\", length(unique(occurrences$countryCode)), \"\\n\")",
  "```",
  "",
  "## Interactive Map",
  "",
  "```{r interactive-map}",
  "#| fig-height: 8",
  "",
  "# Create color palette based on year",
  "occurrences$year <- as.numeric(format(as.Date(occurrences$eventDate), \"%Y\"))",
  "year_range <- range(occurrences$year, na.rm = TRUE)",
  "",
  "# Create color palette",
  "pal <- colorNumeric(",
  "  palette = \"viridis\",",
  "  domain = year_range,",
  "  na.color = \"gray\"",
  ")",
  "",
  "# Create the map",
  "map <- leaflet(occurrences) %>%",
  "  addTiles() %>%",
  "  setView(lng = map_center_lon, lat = map_center_lat, zoom = initial_zoom) %>%",
  "  ",
  "  # Add occurrence points",
  "  addCircleMarkers(",
  "    lng = ~decimalLongitude,",
  "    lat = ~decimalLatitude,",
  "    radius = 5,",
  "    color = ~pal(year),",
  "    stroke = TRUE,",
  "    weight = 1,",
  "    opacity = 0.8,",
  "    fillOpacity = 0.6,",
  "    popup = ~paste(",
  "      \"<strong>\", scientificName, \"</strong><br>\",",
  "      \"Date:\", eventDate, \"<br>\",",
  "      \"Location:\", locality, \"<br>\",",
  "      \"<a href='https://www.gbif.org/occurrence/\", key, \"' target='_blank'>View on GBIF</a>\"",
  "    )",
  "  ) %>%",
  "  ",
  "  # Add legend",
  "  addLegend(",
  "    pal = pal,",
  "    values = ~year,",
  "    title = \"Collection Year\",",
  "    position = \"bottomright\"",
  "  )",
  "",
  "# Display the map",
  "map",
  "```",
  "",
  "## Data Table",
  "",
  "```{r data-table}",
  "# Create a clean data table for exploration",
  "display_data <- occurrences %>%",
  "  select(",
  "    scientificName,",
  "    eventDate,",
  "    countryCode,",
  "    stateProvince,",
  "    locality,",
  "    decimalLatitude,",
  "    decimalLongitude,",
  "    basisOfRecord",
  "  ) %>%",
  "  arrange(desc(eventDate))",
  "",
  "# Create interactive data table",
  "DT::datatable(",
  "  display_data,",
  "  options = list(",
  "    pageLength = 10,",
  "    scrollX = TRUE",
  "  ),",
  "  caption = paste(\"GBIF occurrence records for\", species_name)",
  ")",
  "```",
  "",
  "## Temporal Analysis",
  "",
  "```{r temporal-analysis}",
  "# Plot records over time",
  "occurrences %>%",
  "  filter(!is.na(year)) %>%",
  "  count(year) %>%",
  "  ggplot(aes(x = year, y = n)) +",
  "  geom_line(color = \"steelblue\", size = 1) +",
  "  geom_point(color = \"steelblue\", size = 2) +",
  "  labs(",
  "    title = paste(\"GBIF Records Over Time:\", species_name),",
  "    x = \"Year\",",
  "    y = \"Number of Records\"",
  "  ) +",
  "  theme_minimal()",
  "```",
  "",
  "## Export Data",
  "",
  "```{r export-data}",
  "# Create outputs directory if it doesn't exist",
  "if (!dir.exists(\"outputs\")) {",
  "  dir.create(\"outputs\")",
  "}",
  "",
  "# Save data to CSV",
  "write.csv(occurrences, ",
  "          file = file.path(\"outputs\", paste0(gsub(\" \", \"_\", species_name), \"_gbif_data.csv\")), ",
  "          row.names = FALSE)",
  "",
  "# Save map as HTML widget",
  "htmlwidgets::saveWidget(",
  "  map, ",
  "  file = file.path(\"outputs\", paste0(gsub(\" \", \"_\", species_name), \"_map.html\")),",
  "  selfcontained = TRUE",
  ")",
  "",
  "cat(\"Files saved to outputs/ folder\\n\")",
  "```",
  "",
  "## Research Questions",
  "",
  "**Answer these questions based on your data analysis:**",
  "",
  "### 1. Spatial Distribution",
  "*Describe the geographic distribution of your species. Are there any notable patterns or gaps?*",
  "",
  "[Your answer here]",
  "",
  "### 2. Temporal Patterns",
  "*What trends do you observe in the collection dates? Are there periods with more or fewer records?*",
  "",
  "[Your answer here]",
  "",
  "### 3. Data Quality",
  "*What is the coordinate uncertainty range for your records? How might this affect your analysis?*",
  "",
  "[Your answer here]",
  "",
  "### 4. Collection Bias",
  "*What types of basis of record are most common? What might this tell you about sampling bias?*",
  "",
  "[Your answer here]",
  "",
  "### 5. Research Applications",
  "*How could you use this data for conservation or ecological research?*",
  "",
  "[Your answer here]"
)
write_file("gbif-species-mapper.qmd", notebook_content)

# 5. Assignment Instructions (NOW AS QMD)
instructions_content <- c(
  "---",
  "title: \"GBIF Species Mapper - Assignment Instructions\"",
  "subtitle: \"Due Date: [INSERT DATE] | Points: 100\"",
  "format:",
  "  html:",
  "    toc: true",
  "    theme: cosmo",
  "---",
  "",
  "## Assignment Overview",
  "",
  "You will use R and Quarto to retrieve, analyze, and visualize species occurrence data from GBIF for a taxonomic group.",
  "",
  "## Assigned Species Groups",
  "",
  "| Student | Taxonomic Group | Example Species |",
  "|---------|----------------|-----------------|",
  "| Student 1 | Large Carnivores | *Puma concolor* |",
  "| Student 2 | Migratory Birds | *Turdus migratorius* |",
  "| Student 3 | Marine Mammals | *Balaenoptera musculus* |",
  "| Student 4 | Pollinators | *Bombus impatiens* |",
  "| Student 5 | Reptiles | *Crotalus atrox* |",
  "",
  "::: {.callout-note}",
  "## Instructor Note",
  "Customize the species table above for your specific class assignments.",
  ":::",
  "",
  "## Step-by-Step Instructions",
  "",
  "### Step 1: Repository Setup (5 points)",
  "",
  "- [ ] Accept GitHub Classroom assignment",
  "- [ ] Clone repository to your local machine",
  "- [ ] Open `gbif-species-mapper.qmd` in RStudio",
  "",
  "### Step 2: Species Customization (15 points)",
  "",
  "- [ ] Modify the `species_name` parameter for your assigned species",
  "- [ ] Adjust `country_code` if focusing on a specific region",
  "- [ ] Set appropriate `max_records` (suggest 200-1000)",
  "- [ ] Update map center coordinates for your study area",
  "",
  "### Step 3: Data Analysis (40 points)",
  "",
  "- [ ] Run all code chunks successfully",
  "- [ ] Generate the interactive map with proper styling",
  "- [ ] Create the temporal analysis plot",
  "- [ ] Export CSV and HTML files to outputs folder",
  "",
  "### Step 4: Research Questions (40 points)",
  "",
  "Answer all 5 research questions with thoughtful, detailed responses that demonstrate understanding of the data patterns.",
  "",
  "## Grading Rubric",
  "",
  "| Component | Points | Excellent (A) | Good (B) | Satisfactory (C) | Needs Improvement (D/F) |",
  "|-----------|--------|---------------|----------|------------------|-------------------------|",
  "| **Code Execution** | 25 | All code runs without errors, produces expected outputs | Minor errors that don't affect final results | Some errors but main analysis works | Major errors prevent analysis |",
  "| **Species Customization** | 20 | Appropriate species choice, well-justified parameters | Good species choice, reasonable parameters | Basic customization completed | Minimal or inappropriate customization |",
  "| **Map Quality** | 20 | Professional, informative map with all features working | Good map with minor issues | Basic map functionality | Map missing key features or broken |",
  "| **Analysis & Interpretation** | 20 | Insightful analysis, clear patterns identified | Good analysis with some insights | Basic analysis completed | Superficial or incorrect analysis |",
  "| **Research Questions** | 15 | Thoughtful, detailed answers demonstrating understanding | Good answers showing comprehension | Basic answers meeting requirements | Incomplete or incorrect answers |",
  "",
  "## Tips for Success",
  "",
  "::: {.callout-tip}",
  "## Getting Started",
  "1. **Start early** - GBIF API calls can be slow",
  "2. **Test with small datasets first** - Use `max_records = 50` initially",
  "3. **Check species name spelling** - Verify on GBIF website first",
  "4. **Document your process** - Add comments explaining your choices",
  "5. **Ask for help** - Use GitHub issues or office hours",
  ":::",
  "",
  "## Common Issues and Solutions",
  "",
  "::: {.callout-warning}",
  "## Troubleshooting",
  "",
  "**Species not found error:**",
  "- Check scientific name spelling on [GBIF portal](https://www.gbif.org/)",
  "- Try searching for genus only first",
  "- Use `name_backbone()` function to test species names",
  "",
  "**Too few records:**",
  "- Expand geographic scope (remove country filter)",
  "- Try genus-level search instead of species",
  "- Check if species name has synonyms",
  "",
  "**Map not displaying:**",
  "- Check for missing coordinates",
  "- Verify latitude/longitude are numeric",
  "- Ensure leaflet package is loaded",
  "",
  "**Large file sizes:**",
  "- Reduce `max_records` parameter",
  "- Filter by date range or geographic area",
  "- Remove unnecessary columns before export",
  ":::",
  "",
  "## Submission Requirements",
  "",
  "Your final submission must include:",
  "",
  "1. **Completed Quarto notebook** (`gbif-species-mapper.qmd`) with:",
  "   - Customized parameters for your species",
  "   - All code chunks executed successfully",
  "   - Research questions answered in full sentences",
  "   - Professional formatting and clear explanations",
  "",
  "2. **Generated files** in the `outputs/` folder:",
  "   - HTML report (`gbif-species-mapper.html`)",
  "   - CSV data file (`[species_name]_gbif_data.csv`)",
  "   - Interactive map (`[species_name]_map.html`)",
  "",
  "3. **Git commits** showing your work progress:",
  "   - Initial parameter customization",
  "   - Data retrieval and analysis",
  "   - Final answers and cleanup",
  "",
  "## Academic Integrity",
  "",
  "::: {.callout-important}",
  "## Academic Honesty Policy",
  "- You may discuss general approaches with classmates",
  "- All code and analysis must be your own work",
  "- Properly cite any external resources used",
  "- Do not share your specific species data or code solutions",
  ":::",
  "",
  "## Late Submission Policy",
  "",
  "- 10% deduction per day late",
  "- No submissions accepted after 1 week past due date",
  "- Contact instructor immediately if you anticipate problems",
  "",
  "---",
  "",
  "**Good luck with your analysis!** Remember, the goal is to learn about biodiversity data and spatial analysis, not just complete the assignment."
)
write_file("assignment-instructions.qmd", instructions_content)

# 6. GitHub Actions workflow
workflow_content <- c(
  "name: Render Quarto",
  "",
  "on:",
  "  push:",
  "    branches: [ main, master ]",
  "",
  "jobs:",
  "  render:",
  "    runs-on: ubuntu-latest",
  "    steps:",
  "    - uses: actions/checkout@v3",
  "    - name: Setup R",
  "      uses: r-lib/actions/setup-r@v2",
  "    - name: Setup Quarto",
  "      uses: quarto-dev/quarto-actions/setup@v2",
  "    - name: Install R dependencies",
  "      run: R -e \"install.packages(c('rgbif', 'leaflet', 'dplyr', 'DT', 'htmlwidgets', 'ggplot2'))\"",
  "    - name: Render Quarto",
  "      run: |",
  "        quarto render gbif-species-mapper.qmd",
  "        quarto render assignment-instructions.qmd"
)
write_file(".github/workflows/render-quarto.yml", workflow_content)

cat("\n🎉 Repository structure created successfully in", target_dir, "!\n")
cat("\nFiles created:\n")
cat("- README.md\n")
cat("- .gitignore\n")
cat("- _quarto.yml\n")
cat("- gbif-species-mapper.qmd\n")
cat("- assignment-instructions.qmd (now in Quarto format!)\n")
cat("- .github/workflows/render-quarto.yml\n")
cat("- data/.gitkeep\n")
cat("- outputs/.gitkeep\n")
cat("\nNext steps:\n")
cat("1. cd", target_dir, "\n")
cat("2. git init\n")
cat("3. git add .\n")
cat("4. git commit -m 'Initial commit'\n")
cat("5. Push to GitHub and set up GitHub Classroom\n")
cat("\nAll files are ready for your students!\n")
