name: build-site

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "17 3 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: System deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("sf","dplyr","rgbif","readr","jsonlite","leaflet","crosstalk","htmltools","tidyr","quarto"))'

      - name: Fetch GBIF data
        run: Rscript scripts/fetch_gbif.R

      - name: Render site
        run: Rscript -e 'quarto::quarto_render()'

      - name: Commit updated data & site
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Auto-update GBIF data and site [skip ci]" || echo "Nothing to commit"
          git push
